# Generated by Django 4.2.16 on 2024-11-14 01:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(max_length=254, null=True)),
                ('genre', models.CharField(max_length=64)),
                ('age_rating', models.IntegerField(null=True)),
                ('developer', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=32)),
                ('release', models.DateField()),
                ('cover', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('developer', models.CharField(max_length=32, null=True)),
                ('release', models.DateField()),
                ('manufacturer', models.CharField(max_length=32, null=True)),
                ('processor', models.CharField(max_length=254, null=True)),
                ('graphics', models.CharField(max_length=254, null=True)),
                ('memory', models.CharField(max_length=254, null=True)),
                ('storage', models.CharField(max_length=254, null=True)),
                ('sound', models.CharField(max_length=254, null=True)),
                ('mass', models.CharField(max_length=254, null=True)),
                ('cover', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
        ),
    ]
