# Generated by Django 4.2.16 on 2024-11-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_platform_game_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='console',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.console'),
        ),
        migrations.AddField(
            model_name='product',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.game'),
        ),
    ]
