# Generated by Django 4.2.16 on 2024-11-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_console_cover_remove_game_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='info',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='console',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.console'),
        ),
        migrations.AlterField(
            model_name='product',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.game'),
        ),
    ]
